### ISSUE TITLE
Dealing with variable number of observations in a group

### ISSUE THREAD

**Issue by bdyetton** [junpenglao/Bayesian-Cognitive-Modeling-in-Pymc3#1]
I'm trying to estimate a multi-level model where each group has a different number of observations.
Im not sure how to format my observed variable in this case. 
[This example](https://render.githubusercontent.com/view/ipynb?commit=aa704d89aa1ca76ffa9a477ee37a3a6556c8fbf0&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6a756e70656e676c616f2f426179657369616e2d436f676e69746976652d4d6f64656c696e672d696e2d50796d63332f616137303464383961613163613736666661396134373765653337613361363535366338666266302f506172616d65746572457374696d6174696f6e2f476175737369616e2e6970796e62&nwo=junpenglao%2FBayesian-Cognitive-Modeling-in-Pymc3&path=ParameterEstimation%2FGaussian.ipynb&repository_id=53585763&repository_type=Repository#4.3-Repeated-measurement-of-IQ) from Lee's book, but with `y = np.array([[90, 95, 100, 100], [105, 110, 115], [150, 155, 160]])` is a simple example of what I am trying to do (3 groups, one with more observations than the other).  I get a `ValueError: setting an array element with a sequence.` when attempting to set y to above. What would you suggest?

**Comment by junpenglao** [comment]
Hi @bdyetton, the easiest way is to turn the model into a linear model `Y = X*beta`. In this case, your X will be the predictor for the subject. For example, you can try the code below:
```python
# y as a 1D array:
y = np.array([90, 95, 100, 100, 105, 110, 115, 150, 155, 160])
# predictor vector, you use this to index to mu
x = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int)
nsbj = 3
with pm.Model() as model3:
    # mu_i ~ Uniform(0, 300)
    mui = pm.Uniform('mui', 0, 300, shape=(nsbj,1))

    # sg ~ Uniform(0, 100)
    # sg = pm.Uniform('sg', .0, 100)
    
    # It is more stable to use a Gamma prior
    lambda1 = pm.Gamma('lambda1', alpha=.01, beta=.01)
    sg = pm.Deterministic('sg',1 / np.sqrt(lambda1))
    
    # y ~ Normal(mu_i, sg)
    yd = pm.Normal('y', mu=mui[x], sd=sg, observed=y)
    
    trace3 = pm.sample(1e3, njobs=2)
```

More information on linear model in PyMC3 could be found http://docs.pymc.io/en/latest/examples.html#glm

**Comment by bdyetton** [comment]
Ahh, very nice. Thanks for your help.
